#!/bin/bash
printf "=== Tmux ===\n"
printf "Panes:\n"
printf "  h  = split horizontal\n"
printf "  v  = split vertical\n"
printf "  x  = kill pane\n"
printf "  !  = move pane to new window\n"
printf "  z  = maximize/zoom pane\n"
printf "  C-M-b         = zoom/unzoom pane\n"
printf "  C-M-arrows    = navigate panes\n"
printf "  C-M-S-arrows  = resize panes\n"
printf "  C-M-w         = kill pane\n"
printf "  {  / }        = swap pane left/right\n"
printf "\nWindows:\n"
printf "  c  = new window\n"
printf "  k  = kill window\n"
printf "  r  = rename window\n"
printf "  M-S-arrows    = swap window left/right\n"
printf "  M-1..9 = jump to window\n"
printf "\nSessions:\n"
printf "  C  = new session\n"
printf "  K  = kill session\n"
printf "  R  = rename session\n"
printf "  P  = previous session\n"
printf "  N  = next session\n"
printf "\nOther:\n"
printf "  q  = reload config\n"
        printf "\n=== LazyVim ===\n"
printf "Motions:\n"
printf "  ?  = search\n"
printf "  s  = jump to word\n"
printf "  M-p  = paste below\n"
printf "  , ;  = repeat find backward/forward"
printf "Neo-Tree:\n"
printf "  ?  = help"
printf "  /  = find\n"
printf "  .  = set root\n"
printf "  <bs>  = navigate up"
printf "  <bs>  = navigate up"
